# Generated by Django 5.1.4 on 2025-01-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
