# Generated by Django 5.1.4 on 2024-12-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('image', models.ImageField(upload_to='categories/')),
                ('sku', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diamond_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='products/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('is_arabic_special', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('banner_images', models.ManyToManyField(blank=True, related_name='banner_images', to='products.productimage')),
                ('detail_images', models.ManyToManyField(blank=True, related_name='detail_images', to='products.productimage')),
            ],
        ),
    ]
